### ISSUE TITLE
Broken link to Code of Conduct

### ISSUE THREAD

**Issue by mrengler** [michellelynne/patch-the-pipe#1]
In the README the link to the Code of Conduct is 
https://github.com/michellelynne/patch-the-pipe/blob/master/code_of_conduct.md
but the Code of Conduct is located at 
https://github.com/michellelynne/patch-the-pipe/blob/master/code-of-conduct.md

Super easy fix, but I figured it'd be faster to just tell you. Great work!

**Comment by michellelynne** [comment]
Thanks all fixed!
